Fix window resizing of solidus_chrome_headless driver
Fixes errors similar to the one below when running
`solidus_chrome_headless` in a Solidus extension:

```
  1) Checkout leaving and returning to address step
     Got 0 failures and 2 other errors:

     1.1) Failure/Error: visit spree.root_path

          NoMethodError:
            undefined method `args' for nil:NilClass
          # ./spec/features/checkout_spec.rb:25:in `block (2 levels) in <top (required)>'
          # ./spec/support/confirm_helpers.rb:14:in `block (2 levels) in <top (required)>'
```

According to https://github.com/solidusio/solidus_dev_support/pull/183:

> After updating to cimg/ruby:2.7-browsers, we have a newer version of
Selenium running on CircleCI. As such, we need to define our
configuration in a way that is compatible with the new version.